name: mono_state
description: State Management Lib - reactive and less boilerplate.
homepage: https://github.com/JUkhan/dart_mono_state
version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ">=0.25.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  ajwah_bloc_test: ^0.1.1+2
